config/routes.rb
Rails.application.routes.draw do
  root 'films#index', as: 'home'
  #get 'show' => 'films#show', as: 'show'
  get 'about' => 'films#about', as: 'about'
  get 'sortra' => 'films#sortra', as: 'sortra'
  get 'sortye' => 'films#sortye', as: 'sortye'
  get 'filtering_params' => 'films#filtering_params', as: 'filtering_params'
  resources :films
end

app/models/application_record.rb
require 'carrierwave/orm/activerecord'
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/film.rb
class Film < ApplicationRecord
  mount_uploader :picture, PictureUploader
  include Filterable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_film
  def set_film
    @film = Film.all
  end
  protect_from_forgery with: :exception
end

app/controllers/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  http_basic_authenticate_with name: 'Admin', password: '89141',
                               except: %i[guest show create new]

  def index
    @film = Film.all
  end

  def sortra
    @film = Film.all
    @film = Film.where(params[:title]).order("rating DESC")
  end

  def sortye
    @film = Film.all
    @film = Film.where(params[:title]).order("year DESC")
  end

  def filtering_params
    @film = Film.all
    @film = Film.filter(params.slice(:title, :year, :country, :rating, :kind))
  end

  def new
    @film = Film.new
  end

  def show
    #@film = Film.all
    @film = Film.find(params[:id])
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @file = Film.find(params[:id])

    if(@file.update(film_params))
      redirect_to @file
    else
      render :edit
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to films_path
  end

  def create
    #render plain: params[:film].inspect
    @film = Film.new(film_params)

    if(@film.save)
      redirect_to @film
    else
      render 'new'
    end
  end

  private def film_params
    params.require(:film).permit(:title, :body, :year, :rating, :text, :picture, :country, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/about.html.erb
<h4>Страница</h4>

app/views/films/edit.html.erb
<h3>Редактировать фильм</h3>
<%= form_for :film, url: film_path(@film), method: :patch do |f| %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Локализованное название<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    Год выпуска<br>
    <%= f.text_field(:year, {:class => 'form-control'}) %>
  </p>
  <p>
    Рейтинг<br>
    <%= f.text_field(:rating, {:class => 'form-control'}) %>
  </p>
  <p>
    Текстовое описание<br>
    <%= f.text_field(:text, {:class => 'form-control'}) %>
  </p>
  <p>
    Изображение<br>
    <%= f.file_field :picture %>
  </p>
  <p>
    Страна производства<br>
    <%= f.text_field(:country, {:class => 'form-control'}) %>
  </p>
  <p>
    Жанры<br>
    <%= f.text_field(:kind, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit(:class => 'btn btn-success') %>
  </p>
<% end %>

app/views/films/filtering_params.html.erb
<h2>Отфильтрованные фильмы</h2>
<% @film.each do |film| %>
  <div class="well">
  <p><%= film.title %></p>
  <p><%= film.year %></p>
  <p><%= film.country %></p>
  <p><%= film.rating %></p>
  <p><%= film.kind %></p>
  </div>
<% end %>

app/views/films/index.html.erb
<h1>Все фильмы</h1>
<% @film.each do |film| %>
  <div class="well">
  <p><%= film.title %></p>
  <p><%= film.body %></p>
  <p><%= film.rating %></p>
  <%= link_to "Полная информация о фильме", film_path(film), :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/films/new.html.erb
<h3>Добавление нового фильма</h3>
<%= form_for :film, url: films_path do |f| %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Локализованное название<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    Год выпуска<br>
    <%= f.text_field(:year, {:class => 'form-control'}) %>
  </p>
  <p>
    Рейтинг<br>
    <%= f.text_field(:rating, {:class => 'form-control'}) %>
  </p>
  <p>
    Текстовое описание<br>
    <%= f.text_field(:text, {:class => 'form-control'}) %>
  </p>
  <p>
    Изображение<br>
    <%= f.file_field(:picture) %>
  </p>
  <p>
    Страна производства<br>
    <%= f.text_field(:country, {:class => 'form-control'}) %>
  </p>
  <p>
    Жанры<br>
    <%= f.text_field(:kind, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit(:class => 'btn btn-success') %>
  </p>
<% end %>

app/views/films/show.html.erb
<h1><%= @film.title %></h1>
<p><%= @film.body %></p>
<p><%= @film.year %></p>
<p><%= @film.rating %></p>
<p><%= @film.text %></p>
<p><%= image_tag @film.picture %></p>
<p><%= @film.country %></p>
<p><%= @film.kind %></p>
<hr>
<%= link_to "Редактировать фильм", edit_film_path(@film), :class => 'btn btn-warning' %>
<%= link_to "Удалить информацию", film_path(@film), method: :delete, data: {confirm:"Вы точно хотите удалить запись?"}, :class => 'btn btn-danger' %>

app/views/films/sortra.html.erb
<h2>Отсортированные фильмы</h2>
<% @film.each do |film| %>
  <div class="well">
  <p><%= film.title %></p>
  <p><%= film.body %></p>
  <p><%= film.rating %></p>

  </div>
<% end %>

app/views/films/sortye.html.erb
<h2>Отсортированные фильмы</h2>
<% @film.each do |film| %>
  <div class="well">
  <p><%= film.title %></p>
  <p><%= film.body %></p>
  <p><%= film.year %></p>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Films</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>


  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal"><strong>Films</strong></h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark" href="#"><%= link_to "Список фильмов",films_path %> </span>
        <span class="p-2 text-dark" href="#"><%= link_to "Добавление фильма",new_film_path %> </span>
        <span class="p-2 text-dark" href="#"><%= link_to "Сортировка по рейтингу",sortra_path %> </span>
        <span class="p-2 text-dark" href="#"><%= link_to "Сортировка по году выпуска",sortye_path %> </span>
        <span class="p-2 text-dark" href="#"><%= link_to "Фильтрация",filtering_params_path %> </span>
      </nav>
    </div>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>